### PR TITLE
[finishes 187354275] chat on the App to ask for some information publ…

### PR DESCRIPTION
**Pull request by hozayves**
## Objective

The aim is to enable public information inquiries through the chat feature on the App.

## Modifications

1. Edited `server.ts`.
2. Introduced a new model named "chat".
3. Developed an HTML file named "index.html" to evaluate the functionality of the chat.
4. Created a chat controller for handling "getChats" and "sendFile" functions related to chat.
5. Adjusted routes in both `index.ts` and the new `chatRoute.ts`.

## Testing Guidelines

1. Execute `npm run migrate`.
2. Attempt to access the UI via [http://localhost:8080/api/chats/chatApp](http://localhost:8080/api/chats/chatApp).
3. Additionally, login from different browsers to verify if the chat functionality allows communication.

## Associated Matters

Please mention any relevant issues or pull requests.

## Checklist

Ensure the following tasks are completed before submission:

- [ ] Code adheres to the project's coding standards.
- [ ] Changes are accompanied by relevant tests.
- [ ] Documentation is updated, if applicable.
- [ ] All tests pass successfully.

### CODE REVIEW

**Review by JeanIrad — APPROVED** [review]
incredible work

**Review by princenzmw — APPROVED** [review]
Well done, bro ✌

**Review by P-Rwirangira — APPROVED** [review]
Great work !

**Review by niyontwali — APPROVED** [review]

**Review by amin-leon — APPROVED** [review]
Perfect

**Pull request merged**
