### PR TITLE
modified readme for project guidelines

### PR DESCRIPTION
**Pull request by gracemugwanezak**
## Purpose

To create project backend guidelines

## Changes Made

Modified project's backend readme file

## Testing Instructions

No tests

## Related Issues

No issues

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- [x] Code follows the project's coding standards
- [x] Changes are covered by tests
- [x] Documentation is updated (if applicable)
- [x] All tests pass

### CODE REVIEW

**Review by patrickhag — COMMENTED** [review]
Can you add some info related to database?

**Review by P-Rwirangira — APPROVED** [review]
Great

**Review by Favor-star — APPROVED** [review]
Looks fine to me

**Review by patrickhag — APPROVED** [review]
LGTM ✌️

**Review by niyontwali — APPROVED** [review]
Well done

**Pull request merged**
